<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="property" nsURI="http://www.tetrabox.org/property" nsPrefix="property">
  <eClassifiers xsi:type="ecore:EClass" name="Document">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedImports" upperBound="-1"
        eType="#//Import" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedProperties" upperBound="-1"
        eType="#//Property" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importURI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryProperty" abstract="true" eSuperTypes="#//Property">
    <eTypeParameters name="O"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" containment="true">
      <eGenericType eTypeParameter="#//UnaryProperty/O"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryProperty" abstract="true" eSuperTypes="#//Property">
    <eTypeParameters name="L"/>
    <eTypeParameters name="R"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" containment="true">
      <eGenericType eTypeParameter="#//BinaryProperty/L"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" containment="true">
      <eGenericType eTypeParameter="#//BinaryProperty/R"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanProperty">
    <eGenericSuperTypes eClassifier="#//UnaryProperty">
      <eTypeArguments eClassifier="ecore:EClass ../../org.tetrabox.sequence.model/model/sequence.ecore#//SequenceTerminal"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlwaysProperty">
    <eGenericSuperTypes eClassifier="#//UnaryProperty">
      <eTypeArguments eClassifier="#//Property"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NeverBooleanProperty">
    <eGenericSuperTypes eClassifier="#//UnaryProperty">
      <eTypeArguments eClassifier="ecore:EClass ../../org.tetrabox.sequence.model/model/sequence.ecore#//SequenceTerminal"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NeverSequenceProperty">
    <eGenericSuperTypes eClassifier="#//UnaryProperty">
      <eTypeArguments eClassifier="ecore:EClass ../../org.tetrabox.sequence.model/model/sequence.ecore#//Sequence"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceProperty">
    <eGenericSuperTypes eClassifier="#//UnaryProperty">
      <eTypeArguments eClassifier="ecore:EClass ../../org.tetrabox.sequence.model/model/sequence.ecore#//Sequence"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceTightProperty">
    <eGenericSuperTypes eClassifier="#//UnaryProperty">
      <eTypeArguments eClassifier="ecore:EClass ../../org.tetrabox.sequence.model/model/sequence.ecore#//Sequence"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NextEProperty">
    <eGenericSuperTypes eClassifier="#//UnaryProperty">
      <eTypeArguments eClassifier="ecore:EClass ../../org.tetrabox.sequence.model/model/sequence.ecore#//SequenceTerminal"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NextEventAProperty">
    <eStructuralFeatures xsi:type="ecore:EReference" name="range" eType="ecore:EClass ../../org.tetrabox.sequence.model/model/sequence.ecore#//Range"
        containment="true"/>
    <eGenericSuperTypes eClassifier="#//BinaryProperty">
      <eTypeArguments eClassifier="ecore:EClass ../../org.tetrabox.sequence.model/model/sequence.ecore#//SequenceTerminal"/>
      <eTypeArguments eClassifier="#//Property"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventuallyBooleanProperty">
    <eGenericSuperTypes eClassifier="#//UnaryProperty">
      <eTypeArguments eClassifier="ecore:EClass ../../org.tetrabox.sequence.model/model/sequence.ecore#//SequenceTerminal"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventuallySequenceProperty">
    <eGenericSuperTypes eClassifier="#//UnaryProperty">
      <eTypeArguments eClassifier="ecore:EClass ../../org.tetrabox.sequence.model/model/sequence.ecore#//Sequence"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndProperty">
    <eGenericSuperTypes eClassifier="#//BinaryProperty">
      <eTypeArguments eClassifier="#//Property"/>
      <eTypeArguments eClassifier="#//Property"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbortProperty">
    <eGenericSuperTypes eClassifier="#//BinaryProperty">
      <eTypeArguments eClassifier="#//Property"/>
      <eTypeArguments eClassifier="ecore:EClass ../../org.tetrabox.sequence.model/model/sequence.ecore#//SequenceTerminal"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrPropertyBooleanProperty">
    <eGenericSuperTypes eClassifier="#//BinaryProperty">
      <eTypeArguments eClassifier="#//Property"/>
      <eTypeArguments eClassifier="ecore:EClass ../../org.tetrabox.sequence.model/model/sequence.ecore#//SequenceTerminal"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrBooleanPropertyProperty">
    <eGenericSuperTypes eClassifier="#//BinaryProperty">
      <eTypeArguments eClassifier="ecore:EClass ../../org.tetrabox.sequence.model/model/sequence.ecore#//SequenceTerminal"/>
      <eTypeArguments eClassifier="#//Property"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ImpliesProperty">
    <eGenericSuperTypes eClassifier="#//BinaryProperty">
      <eTypeArguments eClassifier="ecore:EClass ../../org.tetrabox.sequence.model/model/sequence.ecore#//SequenceTerminal"/>
      <eTypeArguments eClassifier="#//Property"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SuffixImplicationProperty">
    <eGenericSuperTypes eClassifier="#//BinaryProperty">
      <eTypeArguments eClassifier="ecore:EClass ../../org.tetrabox.sequence.model/model/sequence.ecore#//SequenceTerminal"/>
      <eTypeArguments eClassifier="#//Property"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OverlappingSuffixImplicationProperty">
    <eGenericSuperTypes eClassifier="#//BinaryProperty">
      <eTypeArguments eClassifier="ecore:EClass ../../org.tetrabox.sequence.model/model/sequence.ecore#//Sequence"/>
      <eTypeArguments eClassifier="#//Property"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EquivalenceProperty">
    <eGenericSuperTypes eClassifier="#//BinaryProperty">
      <eTypeArguments eClassifier="ecore:EClass ../../org.tetrabox.sequence.model/model/sequence.ecore#//SequenceTerminal"/>
      <eTypeArguments eClassifier="ecore:EClass ../../org.tetrabox.sequence.model/model/sequence.ecore#//SequenceTerminal"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UntilProperty">
    <eGenericSuperTypes eClassifier="#//BinaryProperty">
      <eTypeArguments eClassifier="#//Property"/>
      <eTypeArguments eClassifier="ecore:EClass ../../org.tetrabox.sequence.model/model/sequence.ecore#//SequenceTerminal"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BeforeProperty">
    <eGenericSuperTypes eClassifier="#//BinaryProperty">
      <eTypeArguments eClassifier="ecore:EClass ../../org.tetrabox.sequence.model/model/sequence.ecore#//SequenceTerminal"/>
      <eTypeArguments eClassifier="ecore:EClass ../../org.tetrabox.sequence.model/model/sequence.ecore#//SequenceTerminal"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OverlappingUntilProperty">
    <eGenericSuperTypes eClassifier="#//BinaryProperty">
      <eTypeArguments eClassifier="ecore:EClass ../../org.tetrabox.sequence.model/model/sequence.ecore#//SequenceTerminal"/>
      <eTypeArguments eClassifier="ecore:EClass ../../org.tetrabox.sequence.model/model/sequence.ecore#//SequenceTerminal"/>
    </eGenericSuperTypes>
  </eClassifiers>
</ecore:EPackage>
