/*
 * generated by Xtext 2.12.0
 */
package org.tetrabox.property.cs.scoping;

import org.tetrabox.sequence.cs.scoping.SequenceCSScopeProvider;

public abstract class AbstractPropertyCSScopeProvider extends SequenceCSScopeProvider {
}
