/*
 * generated by Xtext 2.10.0
 */
package org.tetrabox.property.cs


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PropertyCSStandaloneSetup extends PropertyCSStandaloneSetupGenerated {

	def static void doSetup() {
		new PropertyCSStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
