/*
 * generated by Xtext 2.12.0
 */
package org.tetrabox.sequence.cs.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSequenceCSScopeProvider extends DelegatingScopeProvider {
}
