/*
 * generated by Xtext 2.10.0
 */
package org.tetrabox.sequence.cs


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SequenceCSStandaloneSetup extends SequenceCSStandaloneSetupGenerated {

	def static void doSetup() {
		new SequenceCSStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
