/*
 * generated by Xtext 2.12.0
 */
package org.tetrabox.property.cs.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.tetrabox.property.cs.services.PropertyCSGrammarAccess;

@SuppressWarnings("all")
public class PropertyCSSyntacticSequencer extends AbstractSyntacticSequencer {

	protected PropertyCSGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Property_LeftParenthesisKeyword_6_0_q;
	protected AbstractElementAlias match_Property_LeftParenthesisKeyword_7_0_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (PropertyCSGrammarAccess) access;
		match_Property_LeftParenthesisKeyword_6_0_q = new TokenAlias(false, true, grammarAccess.getPropertyAccess().getLeftParenthesisKeyword_6_0());
		match_Property_LeftParenthesisKeyword_7_0_q = new TokenAlias(false, true, grammarAccess.getPropertyAccess().getLeftParenthesisKeyword_7_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Property_LeftParenthesisKeyword_6_0_q.equals(syntax))
				emit_Property_LeftParenthesisKeyword_6_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Property_LeftParenthesisKeyword_7_0_q.equals(syntax))
				emit_Property_LeftParenthesisKeyword_7_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     '('?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) 'always' operand=Property
	 *     (rule start) (ambiguity) 'eventually!' operand=Sequence
	 *     (rule start) (ambiguity) 'eventually!' operand=SequenceTerminal
	 *     (rule start) (ambiguity) 'never' operand=Sequence
	 *     (rule start) (ambiguity) 'never' operand=SequenceTerminal
	 *     (rule start) (ambiguity) 'next_e' operand=SequenceTerminal
	 *     (rule start) (ambiguity) operand=Sequence
	 *     (rule start) (ambiguity) operand=SequenceTerminal
	 */
	protected void emit_Property_LeftParenthesisKeyword_6_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) 'next_event_a' '(' left=SequenceTerminal
	 *     (rule start) (ambiguity) left=Sequence
	 *     (rule start) (ambiguity) left=SequenceTerminal
	 */
	protected void emit_Property_LeftParenthesisKeyword_7_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
