/*
 * generated by Xtext 2.12.0
 */
package org.tetrabox.property.cs.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.tetrabox.sequence.cs.validation.SequenceCSValidator;

public abstract class AbstractPropertyCSValidator extends SequenceCSValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>(super.getEPackages());
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.tetrabox.org/property"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.tetrabox.org/sequence"));
		return result;
	}
	
}
